added updated script in selfhosted runner print log workflow

diff --git a/.github/workflows/create_selfhosted_runner_print_logs.yaml b/.github/workflows/create_selfhosted_runner_print_logs.yaml
--- a/.github/workflows/create_selfhosted_runner_print_logs.yaml
+++ b/.github/workflows/create_selfhosted_runner_print_logs.yaml
@@ -54,10 +54,19 @@ jobs:
             # Extract the installer
             tar xzf ./actions-runner-linux-x64-2.313.0.tar.gz
             # Create the runner and start the configuration experience
-            ./config.sh --unattended --url https://github.com/chefgs/linktoqr --token AB2A3GXKLIKGPIBLVCUIT2DFZYGSK
+            ./config.sh --unattended --url https://github.com/chefgs/${{ github.event.inputs.Repo_Name }} --token AB2A3GXKLIKGPIBLVCUIT2DFZYGSK
+            
+            if [ $? -eq 0 ]; then
+                echo "Runner setup successfully completed"
+                # Config.sh installs the service files. 
+                # So as a last step, setup runner service & run it!
+                ./svc.sh install && ./svc.sh start
+            else
+                echo "Runner creation failed"
+                exit 1
+            fi
 
-            # Last step, create service using svc.sh and run it!
-            # Otherwise run the runner using run.sh
+            # Last step, run it!
             ./run.sh &
 
     - name: SSH into Metal Device and Display CloudInit Logs
